---
- name: Test vault_ssh connection plugin
  hosts: all
  connection: cleymax.ansible_global_collection.vault_ssh
  gather_facts: false
  tasks:
    - name: Sleep 30s
      ansible.builtin.pause:
        seconds: 30
    - name: Setup
      ansible.builtin.setup:
        filter:
          - ansible_distribution*
          - ansible_user_id
    - name: Display ansible_distribution
      ansible.builtin.debug:
        msg: "ansible_distribution={{ ansible_distribution }} ansible_user_id={{ ansible_user_id }}"
